layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 13
  exclude:
    archived: false
    forks: false
    projects: ["FoodBook", "learning_pygame_and_opengl","Gewgle", "hexbot", "augur", "ELOSystem", "EntryToHack3.0"]
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: http://weknowyourdreams.com/images/python/python-09.jpg

  - name: Ruby On Rails
    web_url: https://github.com/topics/ruby-on-rails
    image_url: https://pbs.twimg.com/media/CZGHPChUAAA3jqE.png

  - name: Tensorflow
    web_url: https://github.com/topics/Tensorflow
    image_url: https://pbs.twimg.com/profile_images/1103339571977248768/FtFnqC38_400x400.png
